### PR TITLE
convert to node package

### LINKED ISSUE #6: error when running typescript as described in readme
```
❯ tsc --noEmit --allowJs --lib es2015,dom *.js
tic_tac_toe.js:730:50 - error TS2551: Property 'webkitAudioContext' does not exist on type 'Window & typeof globalThis'. Did you mean 'AudioContext'?

730 var context = new (window.AudioContext || window.webkitAudioContext)();
                                                     ~~~~~~~~~~~~~~~~~~

  ../../../.nvm/versions/node/v16.14.0/lib/node_modules/typescript/lib/lib.dom.d.ts:2649:13
    2649 declare var AudioContext: {
                     ~~~~~~~~~~~~
    'AudioContext' is declared here.


Found 1 error in tic_tac_toe.js:730
```

### LINKED ISSUE #8: automatic releases don't include attachment
the CI is not uploading the .xdc file when creating a release on tagging

### PR DESCRIPTION
**Pull request by adbenitez**
close #8 
close #6

### CODE REVIEW

**Comment by adbenitez** [comment]
CI currently failing due to #6

**Comment by Simon-Laux** [comment]
while I agree on using bundlers and typescript, I don't know if we actually **need** to convert everything.

**Comment by adbenitez** [comment]
well it is about consistency, I have the webxdc-vite template, and I try to "normalize" all apps to at least have something like that, so maintaining them all is easier and mostly duplicate repetitive work rather than having to jump from npm to yarn, to a python script, to a bash script, to a bash script pulled remotely on CI that then broke because the download link of the script changed (that was the case of this repo) etc.

**Comment by adbenitez** [comment]
ok CI now passes \o/

**Pull request merged**
